server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PROD_DB?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: PROD_USER
    password: PROD_USER
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
      #naming:
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
   # use-new-id-generator-mappings: false
    defer-datasource-initialization: true
    generate-ddl: true

jwt:
  access_expiration_time: 1800000 #30분
  refresh_expiration_time: 86400000 #
  secret: d0289a415e0ac3ba02d8ccbb4cc83d4610a57c8ba3767e08bf1d311969e9efbe